liip_imagine:
   # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem

    # default loader to use for all filter sets
    data_loader: flysystem_loader

    resolvers:
        flysystem_resolver:
            flysystem:
                # use the cached version so we're not checking to
                # see if the thumbnailed file lives on S3 on every request
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
                root_url: '%uploads_base_url%'
                cache_prefix: media/cache

     # default cache resolver for saving thumbnails
    cache: flysystem_resolver
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
    filter_sets:
        squared_thumbnail_small:
            filters:
                thumbnail: { size: [200, 200], mode: outbound }

        squared_thumbnail_medium:
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

        responsive_small:
            filters:
                thumbnail: { size: [300, 200], mode: outbound }


